# Generated by Django 4.2.7 on 2025-09-10 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_type', models.CharField(choices=[('text', 'Text Translation'), ('conversation', 'Real-time Conversation'), ('image', 'Image Translation'), ('summarize', 'Text Summarization')], max_length=20)),
                ('source_language', models.CharField(default='en', max_length=10)),
                ('target_language', models.CharField(default='hi', max_length=10)),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Translation History',
                'verbose_name_plural': 'Translation Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('source_language', models.CharField(max_length=10)),
                ('target_language', models.CharField(max_length=10)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='conversation_audio/')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='translation.conversationroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
