# Generated by Django 4.2.7 on 2025-09-10 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarpieceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('airpods', 'AirPods'), ('galaxy_buds', 'Samsung Galaxy Buds'), ('generic', 'Generic Bluetooth Earpiece'), ('custom', 'Custom Device')], default='generic', max_length=20)),
                ('bluetooth_address', models.CharField(max_length=17, unique=True)),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('paired', 'Paired'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('battery_level', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=False)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('auto_detect_language', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earpiece_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_connected', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EarpieceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('active', 'Active'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='pending', max_length=20)),
                ('room_name', models.CharField(max_length=100, unique=True)),
                ('user1_language', models.CharField(default='en', max_length=10)),
                ('user2_language', models.CharField(default='hi', max_length=10)),
                ('auto_translate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('earpiece1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_earpiece1', to='translation.earpiecedevice')),
                ('earpiece2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_earpiece2', to='translation.earpiecedevice')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earpiece_connections_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earpiece_connections_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
