# Generated by Django 4.2.7 on 2025-09-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_add_conversation_models'),
    ]

    operations = [
        # Remove bluetooth earpiece models
        migrations.DeleteModel(
            name='EarpieceConnection',
        ),
        migrations.DeleteModel(
            name='EarpieceDevice',
        ),
    ]
