# Generated by Django 4.2.7 on 2025-09-20 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translation', '0004_remove_bluetooth_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnBasedConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Partner'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('current_turn', models.CharField(choices=[('user1', 'User 1 Turn'), ('user2', 'User 2 Turn'), ('processing', 'Processing')], default='user1', max_length=20)),
                ('turn_start_time', models.DateTimeField(auto_now_add=True)),
                ('turn_duration', models.IntegerField(default=10)),
                ('total_turns', models.IntegerField(default=0)),
                ('user1_language', models.CharField(default='en', max_length=10)),
                ('user2_language', models.CharField(default='hi', max_length=10)),
                ('room_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_conversations_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_conversations_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TurnBasedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_audio', models.FileField(blank=True, null=True, upload_to='turn_audio/')),
                ('transcribed_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('translated_audio', models.FileField(blank=True, null=True, upload_to='turn_audio/')),
                ('source_language', models.CharField(max_length=10)),
                ('target_language', models.CharField(max_length=10)),
                ('turn_number', models.IntegerField()),
                ('duration', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='translation.turnbasedconversation')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['turn_number', 'timestamp'],
            },
        ),
    ]
