# Generated by Django 4.2.7 on 2025-09-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0005_turnbasedconversation_turnbasedmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessagenew',
            name='session',
        ),
        migrations.RemoveField(
            model_name='conversationmessagenew',
            name='speaker',
        ),
        migrations.RemoveField(
            model_name='conversationroom',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='conversationroom',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='turnbasedconversation',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='turnbasedconversation',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='turnbasedmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='turnbasedmessage',
            name='speaker',
        ),
        migrations.DeleteModel(
            name='ConversationMessage',
        ),
        migrations.DeleteModel(
            name='ConversationMessageNew',
        ),
        migrations.DeleteModel(
            name='ConversationRoom',
        ),
        migrations.DeleteModel(
            name='ConversationSession',
        ),
        migrations.DeleteModel(
            name='TurnBasedConversation',
        ),
        migrations.DeleteModel(
            name='TurnBasedMessage',
        ),
    ]
