# Generated by Django 4.2.7 on 2025-09-21 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translation', '0006_remove_conversation_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AlterField(
            model_name='translationhistory',
            name='translation_type',
            field=models.CharField(choices=[('text', 'Text Translation'), ('conversation', 'Real-time Conversation'), ('image', 'Image Translation'), ('summarize', 'Text Summarization'), ('video', 'Video Summarization')], max_length=20),
        ),
        migrations.CreateModel(
            name='VideoSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('summary_text', models.TextField()),
                ('transcript_text', models.TextField(blank=True)),
                ('summary_words', models.IntegerField(default=0)),
                ('transcript_words', models.IntegerField(default=0)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_summaries', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='translation.video')),
            ],
            options={
                'verbose_name': 'Video Summary',
                'verbose_name_plural': 'Video Summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
