# Generated by Django 4.2.7 on 2025-09-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0007_video_alter_translationhistory_translation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='source_type',
            field=models.CharField(choices=[('upload', 'File Upload'), ('url', 'Video URL')], default='upload', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
